using DeliveryOrder.Domain.Exceptions;
using System;
using System.Threading.Tasks;

namespace DeliveryOrder.Infrastructure.Idempotency
{
    public class RequestManager : IRequestManager
    {
        readonly DeliveryOrderContext _context;
        public RequestManager(DeliveryOrderContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        public async Task<bool> ExistAsync(Guid id)
        {
            var request = await _context.FindAsync<ClientRequest>(id);

            return request != null;
        }

        public async Task CreateRequestForCommandAsync<T>(Guid id)
        {
            var exists = await ExistAsync(id);

            var request = exists ?
                throw new DeliveryOrderDomainException($"Request with {id} already exists") :
                new ClientRequest()
                {
                    Id = id,
                    Name = typeof(T).Name,
                    Time = DateTime.UtcNow
                };

            _context.Add(request);

            await _context.SaveChangesAsync();
        }
    }
}
